spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/YogenRaii/microservice-examples
          search-paths: 'spring-cloud-config-demo' #classpath:/ #located in the $rootDir/config

server:
  port: 8888