spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: C:/Yogen/examples/microservice-examples/spring-cloud-config-demo/config #classpath:/ #located in the $rootDir/config

server:
  port: 8888