server:
  port: ${ZULL_SERVER_PORT:9093}

eureka:
  client:
    serviceUrl:
      defaultZone: ${services.eureka-service.credentials.uri:http://127.0.0.1:8761}/eureka/
zuul:
  routes:
    users:
      path: /users/**
      serviceId: user-service

---
spring:
  profiles: cloud
eureka:
  instance:
    hostname: ${APPLICATION_DOMAIN}
    nonSecurePort: 80